'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../../components/Navbar";
import { Provider } from 'react-redux';
import { store } from './store';
import { PersistGate } from 'redux-persist/integration/react';
import {
  persistReducer,
  persistStore ,
} from 'redux-persist'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const persistor = persistStore(store);

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
      <Navbar />
      {children}
      </PersistGate>
      </Provider>
        </body>
    </html>
  )
}
